### ISSUE TITLE
can't download videos

### ISSUE THREAD

**Issue by legacychimera247** [JannikHv/gydl#12]
thought about opening a new issue to keep the other thread clean...so this is an example
https://www.youtube.com/watch?v=m0UY863XL68
or https://www.youtube.com/watch?v=lHomCiPFknY
none of them are working so far...

**Comment by AsavarTzeth** [comment]
You still did not mention what settings you used, so I assume you used the default settings.

Anyhow, once more I could not reproduce the issue. If you run it from the terminal do you get any useful output? Perhaps it could give some indicator as to where the issue originates?

**Comment by JannikHv** [comment]
It's probably the "requested format not available" error. I've tried it and yes, your videos can't be downloaded in ANY format. For example, try downloading your second video as mp4 and 360p, it'll work. Youtube-dl itself can't format any video to the desired format, it's not a Gydl issue.

I understand that this issue is pretty annoying though, thinking about creating another error window for exactly this error (format).

**Comment by legacychimera247** [comment]
well if it's just a youtube fault, then it's ok to me...i can close this one...
i was reporting this since i've tried all the formats in both 720 and 480 and they were all giving me errors, so i assumed there was something related to my codecs installation...

**Comment by AsavarTzeth** [comment]
Well since I never seem get any real information to work with, as requested several times, I am tempted to give up.
